### ISSUE TITLE
subprocess.CalledProcessError: Command '['sh', '/app/prestart.sh']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by HericsonRamos** [whythawk/full-stack-fastapi-postgresql#5]
Hi Guys!!

I need help please!

my backend container don't work!

` ensure this value has at least 8 characters (type=value_error.any_str.min_length; limit_value=8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/inboard/start.py", line 125, in <module>
    run_pre_start_script(logger=logger)
  File "/app/inboard/start.py", line 26, in run_pre_start_script
    subprocess.run([process, pre_start_path], check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', '/app/prestart.sh']' returned non-zero exit status 1.
 *  Terminal will be reused by tasks, press any key to close it`

**Comment by turukawa** [comment]
@HericsonRamos Is that related to minimum password length?

**Comment by turukawa** [comment]
Closing for lack of response.
